'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Monitor, RefreshCw, Search, Wifi, WifiOff, AlertTriangle, HelpCircle, Plus, Ticket } from 'lucide-react';
import ModuleShell from '@/shared/components/ModuleShell';
import { listDevicesDetailed, type Device } from '@/lib/devices';
import { useWorkspace } from '@/shared/context/WorkspaceContext';

type StatusFilter = 'all' | 'online' | 'offline' | 'overdue' | 'unknown';
type TypeFilter = 'all' | 'server' | 'workstation' | 'network' | 'esxi';
function statusMeta(status?: string) { const s=(status||'unknown').toLowerCase(); if(s==='online')return{label:'Online',className:'bg-emerald-50 text-emerald-800 border-emerald-200',dot:'bg-emerald-500',Icon:Wifi}; if(s==='overdue')return{label:'Overdue',className:'bg-amber-50 text-amber-900 border-amber-200',dot:'bg-amber-500',Icon:AlertTriangle}; if(s==='offline')return{label:'Offline',className:'bg-slate-100 text-slate-700 border-slate-200',dot:'bg-slate-400',Icon:WifiOff}; return{label:'Unknown',className:'bg-slate-50 text-slate-600 border-slate-200',dot:'bg-slate-300',Icon:HelpCircle}; }
function deviceClass(d: Device): TypeFilter { const hay=[d.platform,d.hostname,d.name,(d as any).device_type,(d as any).type].filter(Boolean).join(' ').toLowerCase(); if(/\besxi\b|hypervisor|vcenter|vmware/.test(hay))return'esxi'; if(/\bserver\b|windows server|linux server|datacenter/.test(hay))return'server'; if(/\bswitch\b|\brouter\b|\bfirewall\b|\bap\b|network/.test(hay))return'network'; return'workstation'; }
function deviceTypeLabel(d: Device){const explicit=(d as any).device_type||(d as any).type;if(explicit)return String(explicit);const c=deviceClass(d);return c==='server'?'Server':c==='network'?'Network':c==='esxi'?'ESXi':'Laptop';}
function osLabel(d: Device){return (d as any).os_name||d.platform||'—';}
function lastUser(d: Device){return (d as any).last_user||(d as any).logged_in_user||(d as any).username||'—';}

export default function DevicesPage(){
 const {organizationId,siteId}=useWorkspace();
 const [devices,setDevices]=useState<Device[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [q,setQ]=useState(''); const [filter,setFilter]=useState<StatusFilter>('all'); const [typeFilter,setTypeFilter]=useState<TypeFilter>('all');
 const load=useCallback(async()=>{try{setLoading(true);setError('');const rows=await listDevicesDetailed();const list=Array.isArray(rows)?rows:Array.isArray((rows as any)?.devices)?(rows as any).devices:[];setDevices(list);}catch(e){setError(e instanceof Error?e.message:'Failed to load devices');setDevices([]);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),15000);return()=>clearInterval(id);},[load]);
 const scoped=useMemo(()=>devices.filter((d)=>{const org=d.organization_id??(d as any).organizationId;const site=d.site_id??(d as any).siteId;if(organizationId&&org!=null&&String(org)!==String(organizationId))return false;if(siteId&&site!=null&&String(site)!==String(siteId))return false;return true;}),[devices,organizationId,siteId]);
 const filtered=useMemo(()=>{const query=q.trim().toLowerCase();return scoped.filter((d)=>{const status=(d.status||'unknown').toLowerCase();if(filter!=='all'&&status!==filter)return false;if(typeFilter!=='all'&&deviceClass(d)!==typeFilter)return false;if(!query)return true;return [d.hostname,d.name,d.ip_address,d.agent_id,d.id,d.platform,lastUser(d),osLabel(d)].filter(Boolean).join(' ').toLowerCase().includes(query);});},[scoped,filter,typeFilter,q]);
 const typeCounts=useMemo(()=>{const c={all:scoped.length,server:0,workstation:0,network:0,esxi:0};for(const d of scoped)c[deviceClass(d)]++;return c;},[scoped]);
 const counts=useMemo(()=>{const c={all:scoped.length,online:0,offline:0,overdue:0,unknown:0};for(const d of scoped){const s=(d.status||'unknown').toLowerCase();if(s in c)(c as any)[s]++;else c.unknown++;}return c;},[scoped]);
 return <ModuleShell title="Devices" subtitle="Live endpoints from agent heartbeats. Devices are restricted to the active customer/site context." breadcrumbs={[{label:'Sites',href:'/msp'},{label:'All Sites',href:'/msp'},{label:'Devices'}]} actions={<><Link href="/agents" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><Plus size={16}/>Add Device</Link><Link href="/itsm" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><Ticket size={16}/>Create Ticket</Link><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></>}>
  <div className="mb-4 flex flex-wrap gap-2">{([['all','Total',typeCounts.all],['server','Server',typeCounts.server],['workstation','Workstation',typeCounts.workstation],['network','Network',typeCounts.network],['esxi','ESXi',typeCounts.esxi]] as const).map(([key,label,count])=><button key={key} type="button" onClick={()=>setTypeFilter(key)} className={'inline-flex items-center gap-2 rounded-xl border px-3.5 py-2 text-sm font-medium '+(typeFilter===key?'border-indigo-300 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white text-slate-600')}>{label}<span className="rounded-md bg-slate-100 px-1.5 py-0.5 text-xs font-semibold">{count}</span></button>)}</div>
  <div className="mb-4 flex flex-wrap items-center gap-2">{(['all','online','offline','overdue','unknown'] as StatusFilter[]).map(key=><button key={key} type="button" onClick={()=>setFilter(key)} className={'rounded-full border px-3 py-1 text-xs font-medium capitalize '+(filter===key?'border-indigo-200 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white text-slate-600')}>{key} ({(counts as any)[key]??0})</button>)}<div className="relative ml-auto min-w-[200px] max-w-sm flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search hostname, user, OS, IP…" className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm"/></div></div>
  {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-3"><h2 className="text-sm font-semibold text-slate-900">Managed Devices <span className="ml-2 font-normal text-slate-400">({filtered.length})</span></h2><p className="text-xs text-slate-500">{organizationId?'Customer context active':'No customer selected'}{siteId?' · Site context active':''}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-slate-100 bg-slate-50/80 text-[11px] font-semibold uppercase tracking-wide text-slate-500"><th className="px-3 py-2.5">Hostname</th><th className="px-3 py-2.5">Type</th><th className="px-3 py-2.5">Status</th><th className="px-3 py-2.5">Last User</th><th className="px-3 py-2.5">OS</th><th className="px-3 py-2.5">Last Seen</th></tr></thead><tbody>{loading&&devices.length===0?<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">Loading devices…</td></tr>:filtered.length===0?<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No devices match the active context and filters.</td></tr>:filtered.map((d,i)=>{const meta=statusMeta(d.status);return <tr key={String(d.id||i)} className="border-b border-slate-50 hover:bg-slate-50"><td className="px-3 py-3"><Link href={`/devices/${encodeURIComponent(String(d.id))}`} className="font-medium text-indigo-700 hover:underline">{d.hostname||d.name||d.id}</Link><div className="text-xs text-slate-500">{d.ip_address||d.agent_id||'—'}</div></td><td className="px-3 py-3">{deviceTypeLabel(d)}</td><td className="px-3 py-3"><span className={'inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-xs '+meta.className}><span className={'h-1.5 w-1.5 rounded-full '+meta.dot}/>{meta.label}</span></td><td className="px-3 py-3 text-slate-600">{lastUser(d)}</td><td className="px-3 py-3 text-slate-600">{osLabel(d)}</td><td className="px-3 py-3 text-slate-500">{(d as any).last_seen||(d as any).last_heartbeat||'—'}</td></tr>;})}</tbody></table></div></div>
 </ModuleShell>;
}
