"""expand_agent_model

Revision ID: 4fa1923c1c82
Revises: 3b8d57b26eeb
Create Date: 2026-07-31 07:22:35.732866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fa1923c1c82'
down_revision: Union[str, Sequence[str], None] = '3b8d57b26eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('device_name', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('machine_guid', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('agent_version', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('platform', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('architecture', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('operating_system', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('os_version', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('manufacturer', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('model', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('serial_number', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('bios_serial', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('cpu_model', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('cpu_cores', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('memory_total_mb', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('disk_total_gb', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('ipv4_address', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('ipv6_address', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('mac_address', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('fqdn', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('domain', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('api_key_hash', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('enrollment_token', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('registration_state', sa.Text(), server_default='pending', nullable=False))
    op.add_column('agents', sa.Column('approved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agents', sa.Column('trusted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agents', sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('agents', sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('heartbeat_interval', sa.Integer(), server_default='30', nullable=False))
    op.add_column('agents', sa.Column('poll_interval', sa.Integer(), server_default='30', nullable=False))
    op.add_column('agents', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('certificate_thumbprint', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('tamper_protection', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agents', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('agents', sa.Column('auto_update', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('agents', sa.Column('command_timeout', sa.Integer(), server_default='300', nullable=False))
    op.add_column('agents', sa.Column('restart_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agents', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('last_error_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_agents_hostname'), 'agents', ['hostname'], unique=False)
    op.create_index(op.f('ix_agents_last_heartbeat'), 'agents', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_agents_last_seen'), 'agents', ['last_seen'], unique=False)
    op.create_index(op.f('ix_agents_machine_guid'), 'agents', ['machine_guid'], unique=True)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_machine_guid'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_seen'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_heartbeat'), table_name='agents')
    op.drop_index(op.f('ix_agents_hostname'), table_name='agents')
    op.drop_column('agents', 'last_error_at')
    op.drop_column('agents', 'last_error')
    op.drop_column('agents', 'restart_count')
    op.drop_column('agents', 'command_timeout')
    op.drop_column('agents', 'auto_update')
    op.drop_column('agents', 'enabled')
    op.drop_column('agents', 'tamper_protection')
    op.drop_column('agents', 'certificate_thumbprint')
    op.drop_column('agents', 'public_key')
    op.drop_column('agents', 'poll_interval')
    op.drop_column('agents', 'heartbeat_interval')
    op.drop_column('agents', 'last_heartbeat')
    op.drop_column('agents', 'registered_at')
    op.drop_column('agents', 'trusted')
    op.drop_column('agents', 'approved')
    op.drop_column('agents', 'registration_state')
    op.drop_column('agents', 'enrollment_token')
    op.drop_column('agents', 'api_key_hash')
    op.drop_column('agents', 'domain')
    op.drop_column('agents', 'fqdn')
    op.drop_column('agents', 'mac_address')
    op.drop_column('agents', 'ipv6_address')
    op.drop_column('agents', 'ipv4_address')
    op.drop_column('agents', 'disk_total_gb')
    op.drop_column('agents', 'memory_total_mb')
    op.drop_column('agents', 'cpu_cores')
    op.drop_column('agents', 'cpu_model')
    op.drop_column('agents', 'bios_serial')
    op.drop_column('agents', 'serial_number')
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'manufacturer')
    op.drop_column('agents', 'os_version')
    op.drop_column('agents', 'operating_system')
    op.drop_column('agents', 'architecture')
    op.drop_column('agents', 'platform')
    op.drop_column('agents', 'agent_version')
    op.drop_column('agents', 'machine_guid')
    op.drop_column('agents', 'device_name')
    # ### end Alembic commands ###
