"""add_rbac_tables

Revision ID: 9c90f16f5032
Revises: abcd1234
Create Date: 2026-07-30 07:03:09.570641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c90f16f5032'
down_revision: Union[str, Sequence[str], None] = 'abcd1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_actions_created', 'actions', ['created_at'], unique=False)
    op.create_index('idx_actions_device', 'actions', ['device_id'], unique=False)
    op.create_index('idx_actions_status', 'actions', ['status'], unique=False)
    op.create_index('idx_actions_tenant', 'actions', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('actions_device_id_fkey'), 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actions', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('agents', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'offline'::text"))
    op.alter_column('agents', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('agents_tenant_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('alerts', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alerts', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_device', 'alerts', ['device_id'], unique=False)
    op.create_index('idx_alerts_resolved', 'alerts', ['resolved'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_tenant', 'alerts', ['tenant_id'], unique=False)
    op.create_index('idx_alerts_type', 'alerts', ['type'], unique=False)
    op.drop_constraint(op.f('alerts_tenant_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_device_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alerts', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('commands_device_id_fkey'), 'commands', type_='foreignkey')
    op.create_foreign_key(None, 'commands', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('compliance_reports', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('compliance_reports', 'framework',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('compliance_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('compliance_reports_tenant_id_fkey'), 'compliance_reports', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_reports', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('device_heartbeats_device_id_fkey'), 'device_heartbeats', type_='foreignkey')
    op.create_foreign_key(None, 'device_heartbeats', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('device_metrics_device_id_fkey'), 'device_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'device_metrics', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hunt_results', 'hunt_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('hunt_results', 'matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hunt_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'hunt_results', 'threat_hunts', ['hunt_id'], ['id'], ondelete='CASCADE')
    op.alter_column('incident_timeline', 'incident_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('incident_timeline', 'event_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incident_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'incident_timeline', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.add_column('incidents', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('incidents', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('incidents', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incidents', 'severity',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_incidents_created', 'incidents', ['created_at'], unique=False)
    op.create_index('idx_incidents_device', 'incidents', ['device_id'], unique=False)
    op.create_index('idx_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('idx_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('idx_incidents_tenant', 'incidents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'incidents', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'technician'::text"))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('profiles_tenant_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'operating_system',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'browser',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'browser_version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'login_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               nullable=False)
    op.drop_constraint(op.f('refresh_tokens_replaced_by_token_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_token_id'], ['id'], ondelete='SET NULL')
    op.add_column('response_actions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('response_actions', 'incident_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('response_actions', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('response_actions', 'action',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('response_actions', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('response_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_response_actions_created', 'response_actions', ['created_at'], unique=False)
    op.create_index('idx_response_actions_device', 'response_actions', ['device_id'], unique=False)
    op.create_index('idx_response_actions_incident', 'response_actions', ['incident_id'], unique=False)
    op.create_index('idx_response_actions_status', 'response_actions', ['status'], unique=False)
    op.create_index('idx_response_actions_tenant', 'response_actions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'response_actions', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'response_actions', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'response_actions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('script_tasks', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('script_tasks', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('script_tasks', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('script_tasks', sa.Column('exit_code', sa.Integer(), nullable=True))
    op.add_column('script_tasks', sa.Column('error_output', sa.Text(), nullable=True))
    op.add_column('script_tasks', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('script_tasks', 'script_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('script_tasks', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('script_tasks', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('script_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'script_tasks', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'script_tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'script_tasks', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_column('script_tasks', 'executed_at')
    op.add_column('scripts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('scripts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('scripts', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scripts', 'shell',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scripts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('telemetry', sa.Column('device_id', sa.UUID(), nullable=False))
    op.add_column('telemetry', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('telemetry', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('telemetry', 'cpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('telemetry', 'memory_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('telemetry', 'disk_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('telemetry', 'uptime',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'telemetry', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'telemetry', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_column('telemetry', 'agent_id')
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('threat_hunts', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('threat_hunts', 'hunt_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('threat_hunts', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('threat_hunts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('threat_hunts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('threat_hunts', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('threat_hunts', 'hunt_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('threat_hunts', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('telemetry', sa.Column('agent_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.alter_column('telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telemetry', 'uptime',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('telemetry', 'disk_usage',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('telemetry', 'memory_usage',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('telemetry', 'cpu_usage',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('telemetry', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('telemetry', 'tenant_id')
    op.drop_column('telemetry', 'device_id')
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scripts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('scripts', 'shell',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('scripts', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('scripts', 'updated_at')
    op.drop_column('scripts', 'description')
    op.add_column('script_tasks', sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'script_tasks', type_='foreignkey')
    op.drop_constraint(None, 'script_tasks', type_='foreignkey')
    op.drop_constraint(None, 'script_tasks', type_='foreignkey')
    op.alter_column('script_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('script_tasks', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('script_tasks', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('script_tasks', 'script_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('script_tasks', 'parameters')
    op.drop_column('script_tasks', 'error_output')
    op.drop_column('script_tasks', 'exit_code')
    op.drop_column('script_tasks', 'completed_at')
    op.drop_column('script_tasks', 'started_at')
    op.drop_column('script_tasks', 'tenant_id')
    op.drop_constraint(None, 'response_actions', type_='foreignkey')
    op.drop_constraint(None, 'response_actions', type_='foreignkey')
    op.drop_constraint(None, 'response_actions', type_='foreignkey')
    op.drop_index('idx_response_actions_tenant', table_name='response_actions')
    op.drop_index('idx_response_actions_status', table_name='response_actions')
    op.drop_index('idx_response_actions_incident', table_name='response_actions')
    op.drop_index('idx_response_actions_device', table_name='response_actions')
    op.drop_index('idx_response_actions_created', table_name='response_actions')
    op.alter_column('response_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('response_actions', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('response_actions', 'action',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('response_actions', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('response_actions', 'incident_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('response_actions', 'tenant_id')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_replaced_by_token_id_fkey'), 'refresh_tokens', 'refresh_tokens', ['replaced_by_token_id'], ['id'])
    op.alter_column('refresh_tokens', 'login_method',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('refresh_tokens', 'browser_version',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'browser',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'operating_system',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'device_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_tenant_id_fkey'), 'profiles', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'technician'::text"))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index('idx_incidents_tenant', table_name='incidents')
    op.drop_index('idx_incidents_status', table_name='incidents')
    op.drop_index('idx_incidents_severity', table_name='incidents')
    op.drop_index('idx_incidents_device', table_name='incidents')
    op.drop_index('idx_incidents_created', table_name='incidents')
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('incidents', 'severity',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incidents', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incidents', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('incidents', 'tenant_id')
    op.drop_constraint(None, 'incident_timeline', type_='foreignkey')
    op.alter_column('incident_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incident_timeline', 'event_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incident_timeline', 'incident_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'hunt_results', type_='foreignkey')
    op.alter_column('hunt_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hunt_results', 'matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hunt_results', 'hunt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'device_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('device_metrics_device_id_fkey'), 'device_metrics', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'device_heartbeats', type_='foreignkey')
    op.create_foreign_key(op.f('device_heartbeats_device_id_fkey'), 'device_heartbeats', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'compliance_reports', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_reports_tenant_id_fkey'), 'compliance_reports', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('compliance_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_reports', 'framework',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('compliance_reports', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'commands', type_='foreignkey')
    op.create_foreign_key(op.f('commands_device_id_fkey'), 'commands', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_device_id_fkey'), 'alerts', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(op.f('alerts_tenant_id_fkey'), 'alerts', 'tenants', ['tenant_id'], ['id'])
    op.drop_index('idx_alerts_type', table_name='alerts')
    op.drop_index('idx_alerts_tenant', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_resolved', table_name='alerts')
    op.drop_index('idx_alerts_device', table_name='alerts')
    op.drop_index('idx_alerts_created', table_name='alerts')
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_tenant_id_fkey'), 'agents', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('agents', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'offline'::text"))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key(op.f('actions_device_id_fkey'), 'actions', 'devices', ['device_id'], ['id'])
    op.drop_index('idx_actions_tenant', table_name='actions')
    op.drop_index('idx_actions_status', table_name='actions')
    op.drop_index('idx_actions_device', table_name='actions')
    op.drop_index('idx_actions_created', table_name='actions')
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    # ### end Alembic commands ###
