"""initial_schema

Revision ID: f7fe09a6851c
Revises: 
Create Date: 2026-07-19 07:16:30.861925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7fe09a6851c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jwt_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('replaced_by_token_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jwt_id'), 'refresh_tokens', ['jwt_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_table('incident_timeline')
    op.drop_table('device_heartbeats')
    op.drop_table('events')
    op.drop_table('tenants')
    op.drop_table('file_tasks')
    op.drop_table('script_tasks')
    op.drop_table('telemetry')
    op.drop_index(op.f('idx_events_device'), table_name='device_events')
    op.drop_index(op.f('idx_events_tenant'), table_name='device_events')
    op.drop_index(op.f('idx_events_time'), table_name='device_events')
    op.drop_index(op.f('idx_events_type'), table_name='device_events')
    op.drop_table('device_events')
    op.drop_table('incidents')
    op.drop_table('commands')
    op.drop_table('device_metrics')
    op.drop_table('actions')
    op.drop_table('automation_log')
    op.drop_table('profiles')
    op.drop_table('threat_hunts')
    op.drop_table('audit_trail')
    op.drop_table('compliance_reports')
    op.drop_table('scripts')
    op.drop_table('agents')
    op.drop_table('hunt_results')
    op.drop_table('response_actions')
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('alerts_device_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_tenant_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'tenant_id')
    op.drop_column('alerts', 'mitre_id')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'mitre_name')
    op.drop_column('alerts', 'resolved')
    op.drop_column('alerts', 'incident_id')
    op.drop_column('alerts', 'threat_score')
    op.drop_column('alerts', 'device_id')
    op.drop_column('alerts', 'type')
    op.add_column('devices', sa.Column('device_id', sa.String(), nullable=True))
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('devices', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'offline'::text"))
    op.alter_column('devices', 'ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_devices_health'), table_name='devices')
    op.drop_index(op.f('idx_devices_last_seen'), table_name='devices')
    op.drop_index(op.f('idx_devices_status'), table_name='devices')
    op.drop_index(op.f('idx_devices_tenant'), table_name='devices')
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.drop_constraint(op.f('devices_tenant_id_fkey'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'hostname')
    op.drop_column('devices', 'tenant_id')
    op.drop_column('devices', 'ram')
    op.drop_column('devices', 'health_score')
    op.drop_column('devices', 'agent_version')
    op.drop_column('devices', 'os')
    op.drop_column('devices', 'missed_heartbeats')
    op.drop_column('devices', 'disk')
    op.drop_column('devices', 'agent_token')
    op.drop_column('devices', 'version')
    op.drop_column('devices', 'cpu')
    op.drop_column('devices', 'created_at')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'consecutive_misses')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('devices', sa.Column('consecutive_misses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('cpu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('agent_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('disk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('missed_heartbeats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('os', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('agent_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('health_score', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('hostname', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('devices_tenant_id_fkey'), 'devices', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.create_index(op.f('idx_devices_tenant'), 'devices', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('idx_devices_last_seen'), 'devices', ['last_seen'], unique=False)
    op.create_index(op.f('idx_devices_health'), 'devices', ['health_score'], unique=False)
    op.alter_column('devices', 'ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'offline'::text"))
    op.alter_column('devices', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('devices', 'device_id')
    op.add_column('alerts', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('threat_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('mitre_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('mitre_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('alerts_tenant_id_fkey'), 'alerts', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('alerts_device_id_fkey'), 'alerts', 'devices', ['device_id'], ['id'])
    op.alter_column('alerts', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('alerts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table('response_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('response_actions_pkey'))
    )
    op.create_table('hunt_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('hunt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hunt_results_pkey'))
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'offline'::text"), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('agents_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey'))
    )
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shell', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scripts_pkey'))
    )
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('framework', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('compliance_reports_pkey'))
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_trail_pkey'))
    )
    op.create_table('threat_hunts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hunt_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('indicator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('threat_hunts_pkey'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'technician'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('profiles_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('profiles_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    op.create_table('automation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_log_pkey'))
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('actions_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('actions_pkey'))
    )
    op.create_table('device_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ram_usage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_metrics_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_metrics_pkey'))
    )
    op.create_table('commands',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('command', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('commands_pkey'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('threat_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_table('device_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('ram_usage', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('network_in', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('network_out', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_events_device_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('device_events_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_events_pkey'))
    )
    op.create_index(op.f('idx_events_type'), 'device_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_events_time'), 'device_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_events_tenant'), 'device_events', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_events_device'), 'device_events', ['device_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uptime', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_pkey'))
    )
    op.create_table('script_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('script_tasks_pkey'))
    )
    op.create_table('file_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('file_tasks_pkey'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_table('device_heartbeats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ram', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('disk', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_heartbeats_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_heartbeats_pkey'))
    )
    op.create_table('incident_timeline',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_timeline_pkey'))
    )
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jwt_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
